PO-604
hmcts/opal-frontend pull request #1105
Opened 2024-12-11 11:22 UTC by iamfrankiemoran

### Jira link
[PO-604](https://tools.hmcts.net/jira/browse/PO-604)

### Change description
- To introduce two new menu items and associated permission based access controls:
- Check and approve draft accounts
- Requires Check and Validate Draft Accounts permission to be displayed
- Manage my draft accounts
- Requires Create and Management Draft Accounts permission

### Testing done
- Tested locally and working as expected

### Checklist
- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-12-16 10:54 UTC, max-holland requested changes

2025-01-03 13:55 UTC, max-holland approved these changes

2025-04-01 14:14 UTC, Arnabsubedi233 approved these changes
LGTM

2025-04-01 14:57 UTC, CadeFaulkner approved these changes

2025-04-01 15:03 UTC, merged